//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Activity_Id { get; set; }
        public int Class_ID { get; set; }
        public string Activity_Name { get; set; }
        public System.DateTime Activity_EDT { get; set; }
    }
}
