//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activity_Tracker = new HashSet<Activity_Tracker>();
        }
    
        public string Activity_Id { get; set; }
        public string CourseBatchId { get; set; }
        public string Activity_Name { get; set; }
        public System.DateTime Activity_SDT { get; set; }
        public System.DateTime Activity_EDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Tracker> Activity_Tracker { get; set; }
        public virtual CourseBatch CourseBatch { get; set; }
    }
}
