//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int Id { get; set; }
        public string BatchId { get; set; }
        public int F_PSNO { get; set; }
        public int P_PSNO { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
