//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Activity_Tracker
    {
        public int Tracker_Id { get; set; }
        public int P_PSNo { get; set; }
        public string Activity_Name { get; set; }
        public string Activity_Status { get; set; }
        public string GitUrl { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
